import type { Provider } from "@/lib/types";

export const providers: Provider[] = [
  {
    id: "marco",
    name: "Marco Diaz",
    avatar: "https://i.pravatar.cc/160?img=12",
    headline: "Licensed Fishing Charter Captain",
    bio: "10+ years running deep-sea fishing charters. I teach beginners everything from rigging and knots to casting and safely landing their first catch.",
    location: "Austin, TX",
    languages: ["English", "Spanish"],
    rating: 4.9,
    reviewCount: 214,
    studentCount: 480,
    yearsExperience: 10,
    verified: true,
    responseTime: "~1 hour",
    completionRate: 98,
  },
  {
    id: "elena",
    name: "Elena Petrova",
    avatar: "https://i.pravatar.cc/160?img=45",
    headline: "Portrait & Lifestyle Photographer",
    bio: "Award-winning portrait photographer. I help beginners understand light, composition, and camera settings through hands-on park sessions.",
    location: "Brooklyn, NY",
    languages: ["English", "Russian"],
    rating: 4.8,
    reviewCount: 168,
    studentCount: 320,
    yearsExperience: 8,
    verified: true,
    responseTime: "~30 min",
    completionRate: 96,
  },
  {
    id: "ahmed",
    name: "Ahmed Hassan",
    avatar: "https://i.pravatar.cc/160?img=33",
    headline: "Saltwater Fishing Guide",
    bio: "20 years fishing these waters. Learn bait selection, knot tying, casting, and how to land your first catch safely.",
    location: "San Diego, CA",
    languages: ["English", "Arabic"],
    rating: 5.0,
    reviewCount: 92,
    studentCount: 140,
    yearsExperience: 20,
    verified: true,
    responseTime: "~2 hours",
    completionRate: 99,
  },
  {
    id: "layla",
    name: "Layla Ahmadi",
    avatar: "https://i.pravatar.cc/160?img=47",
    headline: "Personal Finance & Budgeting Coach",
    bio: "I've helped hundreds of people take control of their money. Together we build a personalized budget and a realistic savings plan.",
    location: "Remote",
    languages: ["English", "Farsi"],
    rating: 4.9,
    reviewCount: 301,
    studentCount: 1020,
    yearsExperience: 7,
    verified: true,
    responseTime: "~15 min",
    completionRate: 97,
  },
  {
    id: "sarah",
    name: "Sarah Connor",
    avatar: "https://i.pravatar.cc/160?img=23",
    headline: "Licensed Plumber & DIY Instructor",
    bio: "Instead of fixing your plumbing, I teach you how. Replace a faucet, stop leaks, and maintain your home with confidence.",
    location: "Denver, CO",
    languages: ["English"],
    rating: 4.7,
    reviewCount: 76,
    studentCount: 190,
    yearsExperience: 12,
    verified: true,
    responseTime: "~1 hour",
    completionRate: 95,
  },
  {
    id: "kenji",
    name: "Kenji Tanaka",
    avatar: "https://i.pravatar.cc/160?img=68",
    headline: "Sushi Chef & Culinary Teacher",
    bio: "Trained in Tokyo. Learn knife skills, rice seasoning, and how to roll restaurant-quality sushi in your own kitchen.",
    location: "Seattle, WA",
    languages: ["English", "Japanese"],
    rating: 4.9,
    reviewCount: 133,
    studentCount: 260,
    yearsExperience: 15,
    verified: true,
    responseTime: "~45 min",
    completionRate: 98,
  },
];

export function getProvider(id: string): Provider | undefined {
  return providers.find((p) => p.id === id);
}

// The signed-in demo user (used on profile / wallet screens).
export const currentUser: Provider = providers[0];
