import type { Service } from "@/lib/types";

const u = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;

export const services: Service[] = [
  {
    id: "deep-cleaning",
    title: "Deep-Sea Fishing for Beginners",
    categoryId: "fishing",
    providerId: "marco",
    coverImage: u("photo-1473116763249-2faaef81ccda"),
    description:
      "Spend the morning out on the water learning to fish from the deck of a real charter boat. From rigging your line to reeling in your first catch, I'll guide you through every step — all gear, bait, and safety equipment included.",
    pricingModel: "hourly",
    price: 80,
    durationMinutes: 120,
    skillLevel: "Beginner",
    teachingMethod: "One-to-one",
    locationType: "Offline",
    rating: 4.9,
    reviewCount: 214,
    studentCount: 480,
    featured: true,
    requirements: [
      "Comfortable, non-slip shoes",
      "Sun protection and a light jacket",
      "All rods, tackle and bait provided",
    ],
    learningOutcomes: [
      "Rig a rod and tie essential fishing knots",
      "Read the water and pick the right bait",
      "Cast accurately and set the hook",
      "Land and safely handle your catch",
    ],
    gallery: [
      u("photo-1473116763249-2faaef81ccda", 400),
      u("photo-1445112098124-3e76dd67983c", 400),
      u("photo-1500964757637-c85e8a162699", 400),
    ],
    distanceKm: 2.4,
  },
  {
    id: "portrait-photography",
    title: "Outdoor Portrait Photography for Beginners",
    categoryId: "photography",
    providerId: "elena",
    coverImage: u("photo-1452587925148-ce544e77e70d"),
    description:
      "Meet me in the park for a hands-on portrait session. We'll work with real models while I explain natural light, composition, and the exact camera settings that make portraits pop.",
    pricingModel: "fixed",
    price: 120,
    durationMinutes: 90,
    skillLevel: "Beginner",
    teachingMethod: "Small group",
    locationType: "Offline",
    rating: 4.8,
    reviewCount: 168,
    studentCount: 320,
    featured: true,
    requirements: [
      "DSLR or mirrorless camera recommended",
      "Comfortable walking shoes",
      "Fully charged battery and empty memory card",
    ],
    learningOutcomes: [
      "Read and use natural light",
      "Compose flattering portraits",
      "Dial in aperture, ISO and shutter speed",
      "Direct and pose your subject",
    ],
    gallery: [
      u("photo-1452587925148-ce544e77e70d", 400),
      u("photo-1554048612-b6a482bc67e5", 400),
      u("photo-1494790108377-be9c29b29330", 400),
    ],
    distanceKm: 5.1,
  },
  {
    id: "saltwater-fishing",
    title: "Learn Saltwater Fishing for Complete Beginners",
    categoryId: "fishing",
    providerId: "ahmed",
    coverImage: u("photo-1500964757637-c85e8a162699"),
    description:
      "Spend three hours at the marina learning everything from selecting bait to landing your very first fish. All gear included — just bring yourself and a sense of adventure.",
    pricingModel: "per_person",
    price: 65,
    durationMinutes: 180,
    skillLevel: "Beginner",
    teachingMethod: "Small group",
    locationType: "Offline",
    rating: 5.0,
    reviewCount: 92,
    studentCount: 140,
    featured: true,
    requirements: [
      "Bring comfortable shoes",
      "Sun protection recommended",
      "All fishing equipment provided",
    ],
    learningOutcomes: [
      "Understand fishing equipment",
      "Tie essential fishing knots",
      "Choose the proper bait",
      "Cast correctly and land a catch safely",
    ],
    gallery: [
      u("photo-1500964757637-c85e8a162699", 400),
      u("photo-1445112098124-3e76dd67983c", 400),
      u("photo-1473116763249-2faaef81ccda", 400),
    ],
    distanceKm: 8.7,
  },
  {
    id: "budgeting",
    title: "Master Your Monthly Budget: Take Control of Your Money",
    categoryId: "life-skills",
    providerId: "layla",
    coverImage: u("photo-1554224155-6726b3ff858f"),
    description:
      "In a focused 1-hour live session we build a personalized budget together, set realistic savings goals, and set up a simple system to track expenses month after month.",
    pricingModel: "hourly",
    price: 45,
    durationMinutes: 60,
    skillLevel: "Beginner",
    teachingMethod: "One-to-one",
    locationType: "Online",
    rating: 4.9,
    reviewCount: 301,
    studentCount: 1020,
    featured: false,
    requirements: [
      "Bring three months of recent bank or expense statements",
      "A spreadsheet app (Google Sheets is fine)",
    ],
    learningOutcomes: [
      "Build a personalized monthly budget",
      "Set realistic savings goals",
      "Track expenses consistently",
      "Reduce debt with a clear plan",
    ],
    gallery: [
      u("photo-1554224155-6726b3ff858f", 400),
      u("photo-1579621970563-ebec7560ff3e", 400),
    ],
    distanceKm: undefined,
  },
  {
    id: "faucet-repair",
    title: "Home Plumbing Basics: Replace a Faucet & Stop Leaks",
    categoryId: "home-repair",
    providerId: "sarah",
    coverImage: u("photo-1607472586893-edb57bdc0e39"),
    description:
      "Save hundreds in future repair costs. I'll walk you through replacing a faucet, fixing common leaks, and maintaining your household plumbing safely.",
    pricingModel: "fixed",
    price: 95,
    durationMinutes: 120,
    skillLevel: "Intermediate",
    teachingMethod: "One-to-one",
    locationType: "Hybrid",
    rating: 4.7,
    reviewCount: 76,
    studentCount: 190,
    featured: false,
    requirements: [
      "Basic hand tools (adjustable wrench, pliers)",
      "Access to the fixture you want to work on",
    ],
    learningOutcomes: [
      "Shut off water safely",
      "Replace a kitchen or bathroom faucet",
      "Diagnose and stop common leaks",
      "Maintain plumbing to prevent damage",
    ],
    gallery: [
      u("photo-1607472586893-edb57bdc0e39", 400),
      u("photo-1585704032915-c3400ca199e7", 400),
    ],
    distanceKm: 3.3,
  },
  {
    id: "sushi-making",
    title: "Handmade Sushi Workshop: Knife Skills & Rolling",
    categoryId: "cooking",
    providerId: "kenji",
    coverImage: u("photo-1579584425555-c3ce17fd4351"),
    description:
      "Trained in Tokyo, I'll teach you restaurant-quality sushi at home — from seasoning the rice to perfect maki rolls and clean knife work.",
    pricingModel: "per_person",
    price: 110,
    durationMinutes: 150,
    skillLevel: "Intermediate",
    teachingMethod: "Workshop",
    locationType: "Offline",
    rating: 4.9,
    reviewCount: 133,
    studentCount: 260,
    featured: true,
    requirements: [
      "Kitchen access required",
      "A sharp knife and cutting board",
      "Ingredients list shared after booking",
    ],
    learningOutcomes: [
      "Season sushi rice correctly",
      "Master basic knife skills",
      "Roll maki and nigiri",
      "Plate like a pro",
    ],
    gallery: [
      u("photo-1579584425555-c3ce17fd4351", 400),
      u("photo-1611143669185-af224c5e3252", 400),
      u("photo-1553621042-f6e147245754", 400),
    ],
    distanceKm: 6.0,
  },
  {
    id: "guitar-basics",
    title: "Acoustic Guitar from Zero: Your First Songs",
    categoryId: "music",
    providerId: "elena",
    coverImage: u("photo-1510915361894-db8b60106cb1"),
    description:
      "Online guitar lessons designed for absolute beginners. Learn chords, strumming patterns, and play your first full song by the end of week one.",
    pricingModel: "hourly",
    price: 40,
    durationMinutes: 60,
    skillLevel: "Beginner",
    teachingMethod: "One-to-one",
    locationType: "Online",
    rating: 4.8,
    reviewCount: 54,
    studentCount: 130,
    featured: false,
    requirements: ["An acoustic or electric guitar", "A quiet room"],
    learningOutcomes: [
      "Play open chords cleanly",
      "Strum in time",
      "Switch chords smoothly",
      "Perform your first song",
    ],
    gallery: [
      u("photo-1510915361894-db8b60106cb1", 400),
      u("photo-1493225457124-a3eb161ffa5f", 400),
    ],
    distanceKm: undefined,
  },
  {
    id: "vegetable-gardening",
    title: "Grow Your Own Vegetables: Backyard Garden Basics",
    categoryId: "gardening",
    providerId: "sarah",
    coverImage: u("photo-1416879595882-3373a0480b5b"),
    description:
      "Turn any backyard or balcony into a productive vegetable garden. Learn soil prep, planting schedules, watering, and pest control the natural way.",
    pricingModel: "fixed",
    price: 70,
    durationMinutes: 120,
    skillLevel: "Beginner",
    teachingMethod: "Small group",
    locationType: "Hybrid",
    rating: 4.6,
    reviewCount: 41,
    studentCount: 95,
    featured: false,
    requirements: ["A small outdoor space or balcony", "Gardening gloves"],
    learningOutcomes: [
      "Prepare healthy soil",
      "Plan a planting schedule",
      "Water efficiently",
      "Manage pests naturally",
    ],
    gallery: [
      u("photo-1416879595882-3373a0480b5b", 400),
      u("photo-1466692476868-aef1dfb1e735", 400),
    ],
    distanceKm: 4.2,
  },
];

export function getService(id: string): Service | undefined {
  return services.find((s) => s.id === id);
}

export const featuredServices = services.filter((s) => s.featured);
export const nearbyServices = services
  .filter((s) => s.distanceKm !== undefined)
  .sort((a, b) => (a.distanceKm ?? 0) - (b.distanceKm ?? 0));
